# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]
  syntax_highlighter: rouge

highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Finn Völkel
tagline:          'Programming, Algorithms, Graph Theory and other stuff'
url:              https://finnvolkel.com
shorturl:         FiV0.github.io

author:
  name:           'Finn Völkel'

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/FiV0/FiV0.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  RSS: '/feed.xml'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-feed

# Jekyll Feed configuration
feed:
  path: feed.xml
